//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytic
    {
        public int AnalyticsID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal TotalSales { get; set; }
        public int NewCustomers { get; set; }
        public Nullable<int> BestsellerProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
