//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int CertificationID { get; set; }
        public int VariantID { get; set; }
        public string Certifier { get; set; }
        public string CertificateNumber { get; set; }
        public string VerificationURL { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
