//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gemstone
    {
        public int GemstoneID { get; set; }
        public int VariantID { get; set; }
        public string Cut { get; set; }
        public string Clarity { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Carat { get; set; }
        public string Origin { get; set; }
        public string Treatment { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
