//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int OrderID { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public string Method { get; set; }
        public string Provider { get; set; }
        public string Status { get; set; }
        public string TransactionRef { get; set; }
        public Nullable<System.DateTime> CapturedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
