//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int WishlistItemID { get; set; }
        public int UserID { get; set; }
        public int VariantID { get; set; }
        public System.DateTime AddedAt { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
        public virtual User User { get; set; }
    }
}
